name: lk-demo
channels:
- lenskit
- defaults
- conda-forge
dependencies:
- python=3.7
- lenskit>=0.9
- pip
- pandas
- scipy
- numba
- cffi
- pyarrow
- fastparquet
- joblib
- tbb
- notebook
- seaborn
- ipython
- implicit
- contextlib2
- statsmodels
- docopt
- line_profiler
- dvc
- papermill
- tensorflow >=2.1
