name: lk-demo
channels:
- lenskit
- defaults
- conda-forge
dependencies:
- python=3.8
- lenskit>=0.9
- pip
- pandas
- scipy
- numba
- cffi
- pyarrow
- tbb
- notebook
- seaborn
- ipython
- implicit
- statsmodels
- docopt
- line_profiler
- dvc
- boto3
- papermill
- tensorflow-gpu >=2.1
